# Generated by Django 5.0.4 on 2024-05-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookModel',
            new_name='ComputerModel',
        ),
    ]
