# Generated by Django 5.0.4 on 2024-05-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_rename_bookmodel_computermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='computermodel',
            name='memory',
            field=models.CharField(choices=[('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB')], max_length=6, null=True),
        ),
    ]
