# Generated by Django 5.0.4 on 2024-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_computermodel_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='computermodel',
            name='computer_picture',
            field=models.ImageField(null=True, upload_to='media/computer-pics'),
        ),
    ]
